server:
  port: 8080
  servlet:
    context-path: /home
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/cinema_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  #    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  signerKey: "vZAWIS53RKXfbNNKEuzpJdS/+/qxK22dSEw5qEMQsHDJwdp7hEmw4BGO9i691dB/"
  valid-duration: 1800 # inseconds
  refreshable-duration: 3600 # inseconds

cloudinary:
  cloud-name: "dod2sfnsr"
  api-key: "821557315416333"
  api-secret: "Ns8TJjf8KhgGaUZ_v_pcML6V_HM"

user:
  id: "0db9151a-65ea-46e9-9e46-13e31e04aaa0"